name: similarity_matcher
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip=23.2.1
  - streamlit=1.24.0
  - pandas=2.0.3
  - numpy=1.24.3
  - pytorch=2.0.0=cpu_*
  - torchvision=0.15.0=cpu_*
  - pip:
    - sentence-transformers==2.2.2
    - transformers==4.30.2